DROP TABLE IF EXISTS Users;
CREATE TABLE Users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    birthdate VARCHAR(10) NOT NULL,
    city VARCHAR(20) NOT NULL,
    country VARCHAR(20) NOT NULL,
    created VARCHAR(10) NOT NULL DEFAULT (DATE(CURRENT_TIMESTAMP))
    );

DROP TABLE IF EXISTS Companies;
CREATE TABLE Companies(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    created VARCHAR(10) NOT NULL DEFAULT (DATE(CURRENT_TIMESTAMP))
    );

DROP TABLE IF EXISTS Products;
CREATE TABLE Products(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) UNIQUE NOT NULL,
    company_id INT NOT NULL,
    points INT NOT NULL,
    created VARCHAR(10) NOT NULL DEFAULT (DATE(CURRENT_TIMESTAMP))
    );

DROP TABLE IF EXISTS Acquisitions;
CREATE TABLE Acquisitions(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_id INT NOT NULL,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    longitude REAL NOT NULL,
    latitude REAL NOT NULL,
    created VARCHAR(10) NOT NULL DEFAULT (DATE(CURRENT_TIMESTAMP))
    );

DROP TABLE IF EXISTS Rewards;
CREATE TABLE Rewards(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_id INT NOT NULL,
    name VARCHAR(50) UNIQUE NOT NULL,
    points INT NOT NULL,
    created VARCHAR(10) NOT NULL DEFAULT (DATE(CURRENT_TIMESTAMP))
    );

DROP TABLE IF EXISTS RedeemedRewards;
CREATE TABLE RedeemedRewards(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    reward_id INT NOT NULL,
    company_id INT NOT NULL,
    user_id INT NOT NULL,
    used INTEGER NOT NULL,
    created VARCHAR(10) NOT NULL DEFAULT (DATE(CURRENT_TIMESTAMP))
    );
